[env:esp32s3box]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32s3box
framework = arduino
board_build.partitions = partitions.csv
lib_compat_mode = strict
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.extra_flags = 
	-DBOARD_HAS_PSRAM
build_flags = 
	-D BOARD_HAS_PSRAM
	-D ARDUINO_USB_MODE=1
	-D CONFIG_ESP_COREDUMP_ENABLE_TO_NONE=1
	-D LV_CONF_INCLUDE_SIMPLE=1
    -I include
	
monitor_speed = 115200
upload_speed = 921600
lib_deps = 
	lvgl/lvgl@^9.6
	ayushsharma82/ElegantOTA@^3.1.7
	lovyan03/LovyanGFX@^1.2.29
